export const COURSES_LIST = [
      {
         id: 1,
         name: '기초 일본어 1반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '10:00 ~ 12:00',
         price: 130000,
      },
      {
         id: 2,
         name: '기초 일본어 2반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '10:00 ~ 12:00',
         price: 130000,
      },
      {
         id: 3,
         name: '기초 일본어 3반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '14:00 ~ 16:00',
         price: 130000,
      },
      {
         id: 4,
         name: '기초 일본어 4반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '14:00 ~ 16:00',
         price: 130000,
      },
      {
         id: 5,
         name: '기초 일본어 5반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '19:00 ~ 21:00',
         price: 130000,
      },
      {
         id: 6,
         name: '기초 일본어 6반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '19:00 ~ 21:00',
         price: 130000,
      },
      {
         id: 7,
         name: '기초 일본어 7반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '10:00 ~ 12:00',
         price: 130000,
      },
      {
         id: 8,
         name: '기초 일본어 8반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '10:00 ~ 12:00',
         price: 130000,
      },
      {
         id: 9,
         name: '기초 일본어 9반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '14:00 ~ 16:00',
         price: 130000,
      },
      {
         id: 10,
         name: '기초 일본어 10반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '14:00 ~ 16:00',
         price: 130000,
      },
      {
         id: 11,
         name: '기초 일본어 11반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '19:00 ~ 21:00',
         price: 130000,
      },
      {
         id: 12,
         name: '기초 일본어 12반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '19:00 ~ 21:00',
         price: 130000,
      },
      {
         id: 13,
         name: '기초 일본어 13반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '10:00 ~ 12:00',
         price: 130000,
      },
      {
         id: 14,
         name: '기초 일본어 14반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '10:00 ~ 12:00',
         price: 130000,
      },
      {
         id: 15,
         name: '기초 일본어 15반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '14:00 ~ 16:00',
         price: 130000,
      },
      {
         id: 16,
         name: '기초 일본어 16반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '14:00 ~ 16:00',
         price: 130000,
      },
      {
         id: 17,
         name: '기초 일본어 17반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '월, 수, 금',
         time: '19:00 ~ 21:00',
         price: 130000,
      },
      {
         id: 18,
         name: '기초 일본어 18반',
         description: '일본어 기초 문법과 회화를 배웁니다.',
         day: '화, 목, 토',
         time: '19:00 ~ 21:00',
         price: 130000,
      },
   ]