
export const realCourses = [
   {
      id: 1,
      title: '원샷반 1',
      mainImageUrl: '/images/real/courses/oneshot1/oneshot1-thumbnail.png',
      detailImages: ['/images/real/oneshot1/oneshot1-1.png', '/images/real/oneshot1/oneshot1-2.png', '/images/real/oneshot1/oneshot1-3.png', '/images/real/oneshot1/oneshot1-4.png'],
      cost: 180000,
      isOnline: true,
      isOffline: true,
      isRecorded: true,
   },
   {
      id: 2,
      title: '원샷반 2',
      mainImageUrl: '/images/real/courses/oneshot2/oneshot2-thumbnail.png',
      detailImages: ['/images/real/oneshot2/oneshot2-1.png', '/images/real/oneshot2/oneshot2-2.png', '/images/real/oneshot2/oneshot2-3.png', '/images/real/oneshot2/oneshot2-4.png'],
      cost: 180000,
      isOnline: true,
      isOffline: true,
      isRecorded: true,
   },
   {
      id: 3,
      title: '원샷반 3',
      mainImageUrl: '/images/real/courses/oneshot3/oneshot3-thumbnail.png',
      detailImages: ['/images/real/oneshot3/oneshot3-1.png', '/images/real/oneshot3/oneshot3-2.png', '/images/real/oneshot3/oneshot3-3.png', '/images/real/oneshot3/oneshot3-4.png'],
      cost: 180000,
      isOnline: true,
      isOffline: true,
      isRecorded: true,
   },
   {
      id: 4,
      title: '예리에몽의 회화포켓',
      mainImageUrl: '/images/real/courses/talk-pocket/talk-pocket-thumbnail.png',
      detailImages: ['/images/real/talk-pocket/talk-pocket-1.png', '/images/real/talk-pocket/talk-pocket-2.png', '/images/real/talk-pocket/talk-pocket-3.png', '/images/real/talk-pocket/talk-pocket-4.png'],
      cost: 190000,
      isOnline: true,
      isOffline: true,
      isRecorded: true,
   },
   {
      id: 5,
      title: '고수들의 회화비밀',
      mainImageUrl: '/images/real/courses/talk-secret/talk-secret-thumbnail.png',
      detailImages: ['/images/real/courses/talk-secret/talk-secret-1.png', '/images/real/courses/talk-secret/talk-secret-2.png', '/images/real/courses/talk-secret/talk-secret-3.png', '/images/real/courses/talk-secret/talk-secret-4.png'],
      cost: 200000,
      isOnline: true,
      isOffline: true,
      isRecorded: true,
   },
   {
      id: 6,
      title: '집에서 원서읽기',
      mainImageUrl: '/images/real/courses/original-reading/original-reading-thumbnail.png',
      detailImages: ['/images/real/courses/original-reading/original-reading-1.png', '/images/real/courses/original-reading/original-reading-2.png', '/images/real/courses/original-reading/original-reading-3.png', '/images/real/courses/original-reading/original-reading-4.png'],
      cost: 100000,
      isOnline: true,
      isOffline: false,
      isRecorded: false,
   },
   {
      id: 7,
      title: '점심회화 무한리필',
      mainImageUrl: '/images/real/courses/infinite-refill/infinite-refill-thumbnail.png',
      detailImages: ['/images/real/courses/infinite-refill/infinite-refill-1.png', '/images/real/courses/infinite-refill/infinite-refill-2.png', '/images/real/courses/infinite-refill/infinite-refill-3.png', '/images/real/courses/infinite-refill/infinite-refill-4.png'],
      cost: 150000,
      isOnline: true,
      isOffline: true,
      isRecorded: true,
   }
]